export const CREATE_FISCALIA = "CREATE_FISCALIA";
export const RETRIEVE_FISCALIAS = "RETRIEVE_FISCALIAS";
export const RETRIEVE_FISCALIA = "RETRIEVE_FISCALIA";
export const UPDATE_FISCALIA = "UPDATE_FISCALIA";
export const DELETE_FISCALIA = "DELETE_FISCALIA";
export const DELETE_ALL_FISCALIAS = "DELETE_ALL_FISCALIAS";